micronaut:
  application:
    name: telegramcodigotbot
---
telegram:
  bots:
    codigobot:
      token: '${TOKEN:xxxyyyzzz}'
      at-username: '@PodcastCodigoBot'
      commands:
        help: 'como usar este bot'
        about: 'información sobre este bot'
---
website:
  rss-url: 'https://feed.codigobot.com/rss.xml'